CREATE TABLE Person(
                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                       name VARCHAR(100) NOT NULL,
                       password VARCHAR NOT NULL,
                       role VARCHAR(20) NOT NULL,
                       can_chat BOOLEAN NOT NULL
);

CREATE TABLE Message(
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                        sender_id INT REFERENCES Person(id) ON DELETE CASCADE,
                        text VARCHAR NOT NULL,
                        date DATE NOT NULL
);

SELECT * FROM Person;
SELECT * FROM Message;